name: CAGroup4 mbedded CI Pipeline

on:
   push:
       branches: [ci-test]
   pull_request:
       branches: [ci-test]
   workflow_dispatch:

jobs:
   controlunit-build:
       name: controlunit (ESP-IDF)
       runs-on: ubuntu-latest
       defaults:
           run:
               working-directory: controlunit
       steps:
           - name: Checkout repository
             uses: actions/checkout@v4

           - name: Set up ESP-IDF environment
             uses: espressif/install-esp-idf-action@v1
             with:
               version: "v5.5.1"

           - name: Echo from controlunit
             run: echo "Building controlunit with ESP-IDF for ESP32-S3-Zero"

   sensorunit-build:
       name: sensorunit (PlatformIO Arduino)
       runs-on: ubuntu-latest
       defaults:
           run:
               working-directory: sensorunit
       steps:
           - name: Checkout repository
             uses: actions/checkout@v4

           - name: Set up PlatformIO
             uses: n-vr/setup-platformio-action@v1
             with:
               platformio-version: "6.1.18"

           - name: Echo from sensorunit
             run: echo "Building sensorunit with PlatformIO for Arduino UNO R4 Wifi"
